const degreeOptions = [
  "Bachelor of Architecture (BArch)",
  "Bachelor of Arts (BA, AB, BS, BSc, SB, ScB)",
  "Bachelor of Applied Arts (BAA)",
  "Bachelor of Applied Arts and Science (BAAS)",
  "Bachelor of Design (BDes, or SDes in Indonesia)",
  "Bachelor of Science in Business (BSBA)",
  "Bachelor of Engineering Technology (BSET)",
  "Bachelor of Technology (B.Tech. or B.Tech.)",
  "International Business Economics (BIBE)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Management Studies (BMS)",
  "Bachelor of Administrative Studies",
  "Bachelor of International Business Economics (BIBE)",
  "Bachelor of Commerce (BCom, or BComm)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Business (BBus or BBus)",
  "Bachelor of Management and Organizational Studies (BMOS)",
  "Bachelor of Business Science (BBusSc)",
  "Bachelor of Accountancy (B.Acy. or B.Acc. or B. Accty)",
  "Bachelor of Comptrolling (B.Acc.Sci. or B.Compt.)",
  "Bachelor of Arts in Organizational Management (BAOM)",
  "Bachelor of Computer Science (BCompSc)",
  "Bachelor of Computing (BComp)",
  "Bachelor of Science in Information Technology (BSc IT)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Business Information Systems (BBIS)]",
];

const courseOptions = [
  "Anthropology",
  "Archaeology",
  "Area Studies",
  "Cultural and Ethnic Studies",
  "Economics",
  "Geography",
  "Political Science",
  "Psychology",
  "Sociology",
  "Computer Sciences",
  "Logic",
  "Mathematics",
  "Statistics",
  "Systems Science",
];

const departmentOptions = [
  "Department of Business Economics",
  "Department of East Asian Studies",
  "Department of Instrumental Music",
  "Department of Library and Information Science",
  "Department of Management Sciences (PUMBA)",
  "Department of Computer Science",
  "Department of Electronics",
  "Department of IT",
];

export default {
  degreeOptions,
  courseOptions,
  departmentOptions,
};
